/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pj_asterix;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author pergaixj
 */
public class V_main extends javax.swing.JFrame {
    private M_users utilisateurConnecte;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_main.class.getName());

    private C_asterix leControl;
    private Object unObjet;
    private String classe;
    
    
    private Map<String, Object> menuMap = new HashMap<>();
    private JMenu mn;
    private JMenuItem mi;
    
    private LinkedHashMap <Integer, M_Autorisation> lesAutorisations;
    private M_Autorisation uneAutorisation;
    
    
    public void afficher() {
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        scanMenus(menuBar);
        this.setVisible(true);
        
    }
    
     private void scanMenus(JMenuBar menuBar) {

// Parcourir les éléments de la JMenuBar
        for (int i = 0; i < menuBar.getMenuCount(); i++) {
        mn = menuBar.getMenu(i);
        menuMap.put(mn.getName(), mn);
        if (!"mb_fichier".equals(mn.getName())){  // Vérifier que c'est bien "mb_fichier"
            mn.setVisible(false);
        }

        for (int j = 0; j < mn.getItemCount(); j++) {
            JMenuItem mi = mn.getItem(j);
            if (mi != null) {  // Ajouter cette vérification
                menuMap.put(mi.getName(), mi);
                if (!"mi_quit".equals(mi.getName())){  // Vérifier que c'est bien "mi_quit"
                    mi.setVisible(false);
                }
            }
        }
    }
    } 
    /**
     * Creates new form V_main
     */
    public V_main(C_asterix leControleur) {
        leControl = leControleur;
        initComponents();
    }

    private V_main() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_co = new javax.swing.JPanel();
        tx_login = new javax.swing.JTextField();
        tx_mdp = new javax.swing.JTextField();
        lb_mdp = new javax.swing.JLabel();
        lb_login2 = new javax.swing.JLabel();
        bt_co = new javax.swing.JButton();
        lb_erreur = new javax.swing.JLabel();
        lb_util = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mb_fichier = new javax.swing.JMenu();
        mi_quit = new javax.swing.JMenuItem();
        mb_asterix = new javax.swing.JMenu();
        mi_perso = new javax.swing.JMenuItem();
        mb_divinite = new javax.swing.JMenu();
        mi_divi = new javax.swing.JMenuItem();
        mb_param = new javax.swing.JMenu();
        mi_util = new javax.swing.JMenuItem();
        mi_monCompte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tx_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_mdpActionPerformed(evt);
            }
        });

        lb_mdp.setText("mot de passe :");

        lb_login2.setText("login :");

        bt_co.setText("Connection");
        bt_co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_coActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_coLayout = new javax.swing.GroupLayout(panel_co);
        panel_co.setLayout(panel_coLayout);
        panel_coLayout.setHorizontalGroup(
            panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_coLayout.createSequentialGroup()
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_coLayout.createSequentialGroup()
                                .addComponent(lb_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coLayout.createSequentialGroup()
                                .addComponent(lb_login2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tx_login, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(tx_mdp)))
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(bt_co))
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lb_erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_coLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lb_util, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panel_coLayout.setVerticalGroup(
            panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_coLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lb_util, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_coLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(bt_co)
                .addGap(27, 27, 27))
        );

        mb_fichier.setText("Fichier");
        mb_fichier.setName("mb_fichier"); // NOI18N

        mi_quit.setText("Quitter");
        mi_quit.setName("mi_quit"); // NOI18N
        mi_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_quitActionPerformed(evt);
            }
        });
        mb_fichier.add(mi_quit);

        menuBar.add(mb_fichier);

        mb_asterix.setText("asterix");
        mb_asterix.setName("mb_asterix"); // NOI18N

        mi_perso.setText("Personnage");
        mi_perso.setName("mi_perso"); // NOI18N
        mi_perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_persoActionPerformed(evt);
            }
        });
        mb_asterix.add(mi_perso);

        menuBar.add(mb_asterix);

        mb_divinite.setText("divinités");
        mb_divinite.setName("mb_divinite"); // NOI18N

        mi_divi.setText("Dieux");
        mi_divi.setName("mi_divi"); // NOI18N
        mi_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_diviActionPerformed(evt);
            }
        });
        mb_divinite.add(mi_divi);

        menuBar.add(mb_divinite);

        mb_param.setText("paramétrage");
        mb_param.setName("mb_param"); // NOI18N

        mi_util.setText("Utilisateur");
        mi_util.setName("mi_util"); // NOI18N
        mi_util.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_utilActionPerformed(evt);
            }
        });
        mb_param.add(mi_util);

        mi_monCompte.setText("Mon compte");
        mi_monCompte.setName("mi_monCompte"); // NOI18N
        mi_monCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_monCompteActionPerformed(evt);
            }
        });
        mb_param.add(mi_monCompte);
        mi_monCompte.getAccessibleContext().setAccessibleName("monCompte");

        menuBar.add(mb_param);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_co, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_quitActionPerformed
        this.formWindowClosing(null);
        System.exit(0);
    }//GEN-LAST:event_mi_quitActionPerformed

    private void mi_persoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_persoActionPerformed
        try {
            leControl.aff_V_Personnage();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_persoActionPerformed

    private void mi_diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_diviActionPerformed
        try {
            leControl.aff_V_Divinite();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_diviActionPerformed

    private void mi_utilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_utilActionPerformed
        try {
            leControl.aff_V_util();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (Exception ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_mi_utilActionPerformed

    private void tx_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_mdpActionPerformed

    private void bt_coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_coActionPerformed
        String motPasse, login;

    motPasse = tx_mdp.getText();
    login = tx_login.getText();

    try {
        M_users utilConnecte = leControl.connection_Util(login, motPasse);
        if (utilConnecte == null) {
            lb_erreur.setText("erreur de connection");
        } else {
            this.utilisateurConnecte = utilConnecte;
            panel_co.setVisible(false);
            lb_util.setText("Bonjour " + utilConnecte.getName());

            lesAutorisations = leControl.autorisationRole(utilConnecte.getRoleId());

            for (Integer uneCle : lesAutorisations.keySet()){

                uneAutorisation = lesAutorisations.get(uneCle);

                unObjet = menuMap.get(uneAutorisation.getCode());

                // ✅ AJOUTER CETTE VÉRIFICATION ICI
                if (unObjet != null) {
                    classe = unObjet.getClass().toString();

                    switch(classe){
                        case "class javax.swing.JMenu" -> { 
                            mn = (JMenu) unObjet;
                            mn.setVisible(true);
                        }
                        case "class javax.swing.JMenuItem" -> { 
                            mi = (JMenuItem) unObjet;
                            mi.setVisible(true);
                        }
                    }
                } else {
                    // Debug : afficher le code non trouvé
                    System.out.println("Code non trouvé: " + uneAutorisation.getCode());
                }
            }
        }
    } catch (SQLException ex) {
        System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    } catch (Exception ex) {
        System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
    }//GEN-LAST:event_bt_coActionPerformed

    private void mi_monCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_monCompteActionPerformed
        try {
        // Appeler une nouvelle méthode spécifique pour "Mon Compte"
        leControl.aff_V_MonCompte(utilisateurConnecte);
    } catch (SQLException ex) {
        System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    } catch (Exception ex) {
        System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
    }//GEN-LAST:event_mi_monCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_co;
    private javax.swing.JLabel lb_erreur;
    private javax.swing.JLabel lb_login2;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_util;
    private javax.swing.JMenu mb_asterix;
    private javax.swing.JMenu mb_divinite;
    private javax.swing.JMenu mb_fichier;
    private javax.swing.JMenu mb_param;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mi_divi;
    private javax.swing.JMenuItem mi_monCompte;
    private javax.swing.JMenuItem mi_perso;
    private javax.swing.JMenuItem mi_quit;
    private javax.swing.JMenuItem mi_util;
    private javax.swing.JPanel panel_co;
    private javax.swing.JTextField tx_login;
    private javax.swing.JTextField tx_mdp;
    // End of variables declaration//GEN-END:variables

   private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        try {
            // TODO add your handling code here:

            leControl.deconnexion();
        } catch (SQLException ex) {
            System.getLogger(V_main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    } 
}
