/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pj_asterix;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pergaixj
 */
public class V_Utilisateur_Admin extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Utilisateur_Admin.class.getName());

    private LinkedHashMap<Integer, M_users> lesUtilisateurs;
    private M_users unUtilisateur;
    private LinkedHashMap<Integer, M_role> lesRoles;
    private M_role unRole;
    private DefaultTableModel dm_tb_Util;
    private Integer ligne, iUser, id;
    private C_asterix controler;
    private boolean modeMonCompte = false;
    
    
    /**
     * Creates new form V_Utilisateur_Admin
     */
    public V_Utilisateur_Admin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
public void afficher(C_asterix gestionUtilisateur, LinkedHashMap<Integer, M_users> lesUtilisateurs, LinkedHashMap<Integer, M_role> lesRoles) {
        this.lesUtilisateurs = lesUtilisateurs;
        this.lesRoles = lesRoles;
        this.controler = gestionUtilisateur;
        this.modeMonCompte = false;

        dm_tb_Util = (DefaultTableModel) table_util.getModel();
        dm_tb_Util.setRowCount(lesUtilisateurs.size());
        ligne = 0;

        for (Integer uneCle : lesUtilisateurs.keySet()) {
            unUtilisateur = lesUtilisateurs.get(uneCle);
            table_util.setValueAt(unUtilisateur.getId(), ligne, 0);
            table_util.setValueAt(unUtilisateur.getName(), ligne, 1);
            ligne++;
        }
        list_role.removeAllItems();
        for (Integer uneCle : lesRoles.keySet()) {
            unRole = lesRoles.get(uneCle);
            list_role.addItem(unRole.getCode());
            ligne++;
        }
        

        this.setSize(800, 350);
        this.setLocationRelativeTo(null);

        b_Modif.setVisible(true);
        b_Suppr.setVisible(true);
        b_Ajout.setVisible(true);
        
        setVisible(true);
    }

private void sePlacer() {
        iUser = table_util.getSelectedRow();

        id = (Integer) table_util.getValueAt(iUser, 0);

        tx_id.setEditable(false);
        tx_mdp.setEditable(true);
        unUtilisateur = lesUtilisateurs.get(id);
        tx_id.setText(String.valueOf(unUtilisateur.getId()));
        tx_name.setText(unUtilisateur.getName());
        tx_mail.setText(unUtilisateur.getEmail());
        
        tx_com.setText(unUtilisateur.getCommentaire());
        
         int roleId = unUtilisateur.getRoleId(); // ou getRole().getId() selon votre modèle
    M_role role = lesRoles.get(roleId);
    if (role != null) {
        list_role.setSelectedItem(role.getCode());
    }

    }
public void clear() {
    id = -1;  // ✅ AJOUTER CETTE LIGNE pour indiquer une création
    tx_mdp.setEditable(true);
    tx_name.setText("");
    tx_mail.setText("");
    tx_com.setText("");
    tx_id.setText("");
    tx_mdp.setText("");  // Mettre vide au lieu de "yen a pas"
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_genre = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_util = new javax.swing.JTable();
        b_Modif = new javax.swing.JButton();
        b_Suppr = new javax.swing.JButton();
        b_Ajout = new javax.swing.JButton();
        l_name = new javax.swing.JLabel();
        l_email = new javax.swing.JLabel();
        l_id = new javax.swing.JLabel();
        l_commentaire = new javax.swing.JLabel();
        l_mdp = new javax.swing.JLabel();
        tx_name = new javax.swing.JTextField();
        tx_id = new javax.swing.JTextField();
        tx_mail = new javax.swing.JTextField();
        tx_com = new javax.swing.JTextField();
        tx_mdp = new javax.swing.JTextField();
        bt_enregistrer = new javax.swing.JButton();
        bt_annuler = new javax.swing.JButton();
        l_role = new javax.swing.JLabel();
        list_role = new javax.swing.JComboBox<>();
        b_Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_util.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_util.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_utilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_util);

        b_Modif.setText("Modifier");
        b_Modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ModifActionPerformed(evt);
            }
        });

        b_Suppr.setText("Supprimer");
        b_Suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SupprActionPerformed(evt);
            }
        });

        b_Ajout.setText("Ajouter");
        b_Ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AjoutActionPerformed(evt);
            }
        });

        l_name.setText("name :");

        l_email.setText("mail :");

        l_id.setText("id :");

        l_commentaire.setText("commentaire :");

        l_mdp.setText("mot de passe :");

        tx_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_idActionPerformed(evt);
            }
        });

        bt_enregistrer.setText("Enregistrer");
        bt_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enregistrerActionPerformed(evt);
            }
        });

        bt_annuler.setText("Annuler");
        bt_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_annulerActionPerformed(evt);
            }
        });

        l_role.setText("role :");

        list_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        list_role.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                list_roleAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        list_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_roleActionPerformed(evt);
            }
        });

        b_Retour.setText("Retour");
        b_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_RetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(l_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(513, 513, 513))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_Ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_Suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l_name)
                                        .addGap(40, 40, 40)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tx_com, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tx_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l_role, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(list_role, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(b_Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_Suppr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_Ajout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_role, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_commentaire, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_com, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void afficherMonCompte(C_asterix gestionUtilisateur, M_users utilisateur, LinkedHashMap<Integer, M_role> lesRoles) {
    this.lesRoles = lesRoles;
    this.controler = gestionUtilisateur;
    this.unUtilisateur = utilisateur;
    this.id = utilisateur.getId();
     this.modeMonCompte = true;
    
    // Créer un LinkedHashMap avec uniquement cet utilisateur
    this.lesUtilisateurs = new LinkedHashMap<>();
    this.lesUtilisateurs.put(utilisateur.getId(), utilisateur);

    // Remplir le tableau avec uniquement cet utilisateur
    dm_tb_Util = (DefaultTableModel) table_util.getModel();
    dm_tb_Util.setRowCount(1);
    table_util.setValueAt(utilisateur.getId(), 0, 0);
    table_util.setValueAt(utilisateur.getName(), 0, 1);
    
    // Remplir la liste des rôles
    list_role.removeAllItems();
    for (Integer uneCle : lesRoles.keySet()) {
        unRole = lesRoles.get(uneCle);
        list_role.addItem(unRole.getCode());
    }

    // Pré-remplir les champs avec les infos de l'utilisateur
    tx_id.setText(String.valueOf(utilisateur.getId()));
    tx_id.setEditable(false);
    tx_name.setText(utilisateur.getName());
    tx_mail.setText(utilisateur.getEmail());
    tx_mdp.setEditable(true);  // Ne pas permettre de modifier le mdp directement ici
    tx_com.setText(utilisateur.getCommentaire());
    
    // Sélectionner le rôle actuel
    int roleId = utilisateur.getRoleId();
    M_role role = lesRoles.get(roleId);
    if (role != null) {
        list_role.setSelectedItem(role.getCode());
    }
    // Désactiver la modification du rôle (l'utilisateur ne peut pas changer son propre rôle)
    list_role.setEnabled(false);

    this.setSize(760, 600);
    this.setLocationRelativeTo(null);

    // Cacher les boutons non nécessaires
    b_Modif.setVisible(false);
    b_Suppr.setVisible(false);
    b_Ajout.setVisible(false);
    
    // Cacher le tableau car on affiche directement les infos
    jScrollPane1.setVisible(false);
    
    setVisible(true);
}
    private void b_ModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ModifActionPerformed
        if (table_util.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "un utilisateur doit être sélectionné dans le tableau", "Sélection obligatoire", JOptionPane.ERROR_MESSAGE);
        } else {
            
            setSize(760, 1000);
            sePlacer();
        }
    }//GEN-LAST:event_b_ModifActionPerformed

    private void b_AjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AjoutActionPerformed
         tx_id.setEditable(false);
        id = -1;  // ✅ AJOUTER CETTE LIGNE
    clear();
    setSize(760, 1000);
    }//GEN-LAST:event_b_AjoutActionPerformed

    private void b_SupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SupprActionPerformed
         if (table_util.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, 
            "Un utilisateur doit être sélectionné dans le tableau", 
            "Sélection obligatoire", 
            JOptionPane.ERROR_MESSAGE);
    } else {
        // Récupérer l'ID de l'utilisateur sélectionné
        int iUser = table_util.getSelectedRow();
        int idUtilisateur = (Integer) table_util.getValueAt(iUser, 0);
        String nomUtilisateur = (String) table_util.getValueAt(iUser, 1);
        
        // Demander confirmation
        int reponse = JOptionPane.showConfirmDialog(this,
            "Êtes-vous sûr de vouloir supprimer " + nomUtilisateur + " ?",
            "Attention !",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (reponse == JOptionPane.YES_OPTION) {
            controler.supprimerUtil(idUtilisateur);
        }
    }
    }//GEN-LAST:event_b_SupprActionPerformed

    private void bt_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_annulerActionPerformed
         if (modeMonCompte) {
        // ✅ Mode "Mon Compte" : juste fermer la fenêtre
        this.dispose();
    } else {
        // Mode admin : rafraîchir la liste
        afficher(controler, lesUtilisateurs, lesRoles);
    }
    }//GEN-LAST:event_bt_annulerActionPerformed

    private void tx_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_idActionPerformed

    
    private void bt_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enregistrerActionPerformed
       String vName = tx_name.getText();
    String vMail = tx_mail.getText();
    String vCom = tx_com.getText();
    
    String vRoleCode = (String) list_role.getSelectedItem();
    String vMdp = null;

if (!tx_mdp.getText().isEmpty()) {
    vMdp = BCrypt.withDefaults().hashToString(12, tx_mdp.getText().toCharArray());
}
    
    int vRoleId = -1;
    for (Integer key : lesRoles.keySet()) {
        if (lesRoles.get(key).getCode().equals(vRoleCode)) {
            vRoleId = key;
            break;
        }
    }

    int reponse = JOptionPane.showConfirmDialog(this,
        "Êtes-vous sûr de vouloir modifier " + tx_name.getText() + " ?",
        "Attention !",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );
         
    if (reponse == JOptionPane.YES_OPTION) {
        controler.modifierUtil(id, vName, vMail, vCom, vMdp, vRoleId);
        
        // ✅ AJOUTER : Fermer si mode "Mon Compte"
        if (modeMonCompte) {
            JOptionPane.showMessageDialog(this, "Modifications enregistrées !");
            this.dispose();
        }
    }
    }//GEN-LAST:event_bt_enregistrerActionPerformed

    private void table_utilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_utilMouseClicked
       sePlacer();   
    }//GEN-LAST:event_table_utilMouseClicked

    private void list_roleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_list_roleAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_list_roleAncestorAdded

    private void list_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_roleActionPerformed

    }//GEN-LAST:event_list_roleActionPerformed

    private void b_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_RetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_b_RetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                V_Utilisateur_Admin dialog = new V_Utilisateur_Admin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Ajout;
    private javax.swing.JButton b_Modif;
    private javax.swing.JButton b_Retour;
    private javax.swing.JButton b_Suppr;
    private javax.swing.ButtonGroup b_genre;
    private javax.swing.JButton bt_annuler;
    private javax.swing.JButton bt_enregistrer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_commentaire;
    private javax.swing.JLabel l_email;
    private javax.swing.JLabel l_id;
    private javax.swing.JLabel l_mdp;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_role;
    private javax.swing.JComboBox<String> list_role;
    private javax.swing.JTable table_util;
    private javax.swing.JTextField tx_com;
    private javax.swing.JTextField tx_id;
    private javax.swing.JTextField tx_mail;
    private javax.swing.JTextField tx_mdp;
    private javax.swing.JTextField tx_name;
    // End of variables declaration//GEN-END:variables
}
